### ISSUE TITLE
Jogamp Library

### ISSUE THREAD

**Issue by kidconan3879** [Dewott/GLCytus#1]
released version of glcytus's stderr file prints "Cant load IA 32-bit dll on AMD 64-bit platform.
if I change jogamp library 2.2.4's 64-bit dll, it prints cant load IA ~~ too.
if I change jogamp 2.4's 64-bit dll, it prints java.lang.UnsatisfiedLinkError: jogamp.common.os.MachineDescriptionRuntime.getPointerSizeInByteImpl().
What should I doo?

**Comment by Klomi** [comment]
[http://stackoverflow.com/questions/25699919/running-opengl-jogamp-from-jar](url)
